name: russian-text-classification
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10.2  
  - pip=23.1.2
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.4.2
  - scipy=1.10.1
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - jupyter=1.0.0
  - tqdm=4.65.0
  - pyyaml=6.0.1
  - ipython=8.12.0  
  - requests=2.31.0  
  - pytest=7.4.0  
  - pytest-cov=4.1.0  
  - pip:
    - torch==2.2.1
    - torchvision==0.17.1
    - razdel==0.5.0
    - pymorphy2==0.9.1
    - pymorphy2-dicts-ru==2.4.417127.4579844
    - datasets==2.14.5