pipeline:
  name: "P3"
  steps:
    - clean_text
    - lowercase
    - remove_stopwords  
    - lemmatization
  description: "Базовая очистка + лемматизация"

parameters:
  clean_text:
    remove_html: true
    remove_numbers: true
    remove_punctuation: true
    remove_extra_spaces: true
  lowercase: true
  remove_stopwords:
    language: "russian"
  lemmatization:
    language: "russian"
    method: "pymorphy2"